package sbnz.integracija;
import ftn.sbnz.SBNZBackend.model.Konfiguracija;
import ftn.sbnz.SBNZBackend.model.Zahtevi;
import ftn.sbnz.SBNZBackend.model.GPU;
import ftn.sbnz.SBNZBackend.model.CPU;
import ftn.sbnz.SBNZBackend.model.HardDrive;

global Zahtevi zahtevi;

rule "GPU konfiguracije je od istog proizvodjaca kao i u zahtevu"
    salience 93
    when
        $k : Konfiguracija( getSkor().getGpuProizvodjac() == 0, getGpu().getIme() contains zahtevi.getPrefGpu() )
    then
        modify($k){getSkor().setGpuProizvodjac(10)}
end

rule "CPU konfiguracije je od istog proizvodjaca kao i u zahtevu"
    salience 92
    when
        $k : Konfiguracija( getSkor().getCpuProizvodjac() == 0, getCpu().getIme() contains zahtevi.getPrefCpu() )
    then
        modify($k){getSkor().setCpuProizvodjac(10)}
end