package sbnz.integracija;
import ftn.sbnz.SBNZBackend.model.Konfiguracija;
import ftn.sbnz.SBNZBackend.model.Zahtevi;
import ftn.sbnz.SBNZBackend.model.GPU;
import ftn.sbnz.SBNZBackend.model.CPU;
import ftn.sbnz.SBNZBackend.model.HardDrive;

global Zahtevi zahtevi;

rule "Za web surfing, memorija"
    salience 66
    when
        $k : Konfiguracija( getSkor().getMemorijaHardDisk() == 0, zahtevi.getUpotreba() == "web surfing", $hardDrives : getHardDrives() )
        HardDrive( getMemorija() >= 250 ) from $hardDrives
    then
        modify($k){getSkor().setMemorijaHardDisk(10)}
end

rule "Za web surfing, RAM memorija"
    salience 65
    when
        $k : Konfiguracija( getSkor().getMemorijaRam() == 0, zahtevi.getUpotreba() == "web surfing", $ram : getRam(), $ram.getMemorija() >= 4 )
    then
        modify($k){getSkor().setMemorijaRam(10)}
end

rule "Za web surfing, GPU memorija"
    salience 64
    when
        $k : Konfiguracija( getSkor().getMemorijaGpu() == 0, zahtevi.getUpotreba() == "web surfing", $gpu : getGpu(), $gpu.getMemorija() >= 2 )
    then
        modify($k){getSkor().setMemorijaGpu(10)}
end

rule "Za web surfing, brzina CPU"
    salience 63
    when
        $k : Konfiguracija( getSkor().getBrzinaCpu() == 0, zahtevi.getUpotreba() == "web surfing", $cpu : getCpu(), $cpu.getBrzina() >= 2.0)
    then
        modify($k){getSkor().setBrzinaCpu(10)}
end

rule "Za web surfing, jezgra CPU"
    salience 62
    when
        $k : Konfiguracija( getSkor().getJezgraCpu() == 0, zahtevi.getUpotreba() == "web surfing", $cpu : getCpu(), $cpu.getJezgra() >= 2)
    then
        modify($k){getSkor().setJezgraCpu(10)}
end

rule "Za web surfing, tredovi CPU"
    salience 61
    when
        $k : Konfiguracija( getSkor().getTredoviCpu() == 0, zahtevi.getUpotreba() == "web surfing", $cpu : getCpu(), $cpu.getTredovi() >= 2)
    then
        modify($k){getSkor().setTredoviCpu(10)}
end
